#!/bin/sh
# Copyright (c) 2023 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

Delirant() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delirant ; s="`dirname "$s"`" ; Delirant ; SCRIPTS="$s" ; } ; SCRIPTS

case "$LOMBRICRC" in "") LOMBRICRC="$HOME/.lombricrc" ;; esac
case "$LOMBRICPATH" in "") LOMBRICPATH="$SCRIPTS/../musqle/util.sh:$SCRIPTS/../musqle/util.oracle.sh:$SCRIPTS/sqlminus.sh" ;; esac

auSecours()
{
	nom="`basename "$0"`"
	cat >&2 << TERMINE
# $nom
# Lanceur d'Outils Multi-Base pour Requêtages sous Interface Consolidée
# © 2023 Guillaume Outters

Utilisation: $nom <commande> <args>…
TERMINE
	exit 1
}

analyserParametresEtLancer()
{
	# Analyse des paramètres.
	
	commmande=
	while [ $# -gt 0 ] ; do
		case "$1" in
			-h) auSecours ;;
			*)
				commande="$1"
				break
				;;
		esac
		shift
	done
	
	case "$commande" in "") auSecours ;; esac
	
	# Chargement des personnalisations.
	
	[ ! -e "$LOMBRICRC" ] || . "$LOMBRICRC"
	
	# Lancement, soit en direct si déjà présente, soit via le $LOMBRICPATH
	
	if command -v "$commande" 2> /dev/null >&2
	then
		"$@"
	else
		local f
		
		IFS=:
		for f in $LOMBRICPATH
		do
			[ -e "$f" ] && grep -q "^$commande()" < "$f" || continue
			unset IFS
			. "$f"
			"$@"
			return
		done
		
		echo "# Commande $commande() introuvable dans: $LOMBRICPATH" >&2
		return 1
	fi
}

analyserParametresEtLancer "$@"
